name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.3]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ci
          MYSQL_USER: tester
          MYSQL_PASSWORD: test
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ctype, curl, dom, fileinfo, filter, hash, mbstring, openssl, pcre, pdo, session, tokenizer, xml

      - name: Install PHP dependencies
        run: composer install -n --prefer-dist

      - name: Install and build JS dependencies
        run: |
          npm ci
          npm run build

      - name: Prepare environment
        run: |
          cp .env.ci .env
          php artisan key:generate -n

      - name: Prepare database
        run: |
          php artisan migrate -n
          php artisan db:seed -n

      - name: Run tests
        run: php artisan test

      - name: Run acceptance tests
        run: vendor/bin/behat
